(() => {
'use strict';
const V='1.6',URL='https://uysrtgyfnwyocdlaeyum.supabase.co',KEY='sb_publishable_CezrTxDDvgs8iAjD7vexNQ_0zVphE8j';
const ALIAS={'Língua Portuguesa':'Português'};
let db,user,bank=[],states=new Map(),q=null,start=0,conf='medium',choice=null,eliminated=new Set(),done=false,ok=0,total=0;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function theme(){if($('#mentorQgTheme'))return;let l=document.createElement('link');l.id='mentorQgTheme';l.rel='stylesheet';l.href='./qg-theme.css?v=1.6';document.head.appendChild(l)}
function version(){document.title='Mentor IA v1.6 — Modo QG';$$('.version-badge').forEach(e=>e.textContent='v1.6');let e=$('[data-view="inicio"] .hero-card .eyebrow');if(e)e.textContent='MENTORA + MODO QG • V1.6'}
function ui(){
if($('[data-view="acervo"]'))return;
let main=$('main'),s=document.createElement('section');if(!main)return;
s.className='view';s.dataset.view='acervo';s.innerHTML=`
<div class="qg-bank-header"><div><span class="qg-kicker">CENTRAL DE QUESTÕES • BANCO PRIVADO</span><h1>Modo QG dos Praças</h1><p>Questões reais do seu acervo, correção pelo gabarito do PDF e orientação da Mentora após cada resposta.</p></div><span class="qg-version">V${V}</span></div>
<div class="bank-stats"><article><span>Disponíveis</span><strong id="bankTotal">—</strong><small>no filtro atual</small></article><article><span>Novas</span><strong id="bankNew">—</strong><small>ainda não vistas</small></article><article><span>Operação</span><strong id="bankSession">0/0</strong><small>acertos / respostas</small></article></div>
<article class="bank-filter-card qg-panel"><div class="qg-panel-title">ARSENAL DE FILTROS</div><div class="bank-filter-grid"><label>Matéria<select id="bankSubject"><option value="">Todas</option></select></label><label>Assunto<select id="bankTopic"><option value="">Todos</option></select></label></div><button class="qg-btn qg-btn-primary" id="bankStartBtn">INICIAR LINHA DE QUESTÕES</button><p id="bankStatus" class="bank-status">Entre na sua conta para carregar seu banco privado.</p></article>
<div id="bankOperational" class="hidden"><div class="qg-timer-bar"><span>⏱ TEMPO NA QUESTÃO</span><span id="bankTimer" class="qg-time-display">00:00</span></div><article id="bankQuestionCard" class="qg-question-card"><div class="qg-meta-info"><span id="bankQuestionMeta">Questão</span><span id="bankQuestionStatus" class="qg-status-badge badge-novo">NOVA</span></div><div class="qg-source-line"><strong id="bankQuestionSubject">Matéria</strong><span>•</span><span id="bankQuestionTopic">Assunto</span><span>•</span><span id="bankQuestionSource">Seu módulo</span></div><div id="bankStatement" class="qg-enunciado"></div><div id="bankAnswers" class="qg-options-list"></div><div class="qg-confidence"><span>CONFIANÇA ANTES DO GABARITO:</span><button data-bank-confidence="low">BAIXA</button><button data-bank-confidence="medium" class="active">MÉDIA</button><button data-bank-confidence="high">ALTA</button></div><div id="bankFeedback" class="qg-comment-box hidden"></div><div class="qg-actions"><span id="bankProgress">Aguardando resposta</span><div><button id="bankConfirmBtn" class="qg-btn qg-btn-confirm hidden">DISPARAR GABARITO</button><button id="bankNextBtn" class="qg-btn hidden">AVANÇAR LINHA DE FRENTE →</button></div></div></article></div>`;
main.appendChild(s);
let nav=$('.bottom-nav');if(nav&&!nav.querySelector('[data-go="acervo"]')){let b=document.createElement('button');b.className='nav-item';b.dataset.go='acervo';b.innerHTML='<span>▣</span><small>Questões</small>';let d=nav.querySelector('[data-go="diagnostico"]');d?d.replaceWith(b):nav.prepend(b)}
let hero=$('[data-view="inicio"] .hero-card');if(hero&&!$('#bankHomeCard')){let c=document.createElement('article');c.id='bankHomeCard';c.className='bank-home-card qg-panel';c.innerHTML='<div><span class="qg-kicker">QG DOS PRAÇAS + MENTORA</span><h2>Treino operacional com questões reais.</h2><p id="bankHomeText">Carregando seu acervo privado…</p></div><button class="qg-btn qg-btn-primary" data-go="acervo">ABRIR CENTRAL DE QUESTÕES</button>';hero.insertAdjacentElement('afterend',c)}
$('#bankStartBtn')?.addEventListener('click',begin);$('#bankConfirmBtn')?.addEventListener('click',confirm);$('#bankNextBtn')?.addEventListener('click',next);
$('#bankSubject')?.addEventListener('change',()=>{topics();counts()});$('#bankTopic')?.addEventListener('change',counts);
s.addEventListener('click',e=>{let c=e.target.closest('[data-bank-confidence]');if(c&&!done){conf=c.dataset.bankConfidence;$$('[data-bank-confidence]').forEach(x=>x.classList.toggle('active',x===c));return}let x=e.target.closest('[data-bank-eliminate]');if(x&&!done){e.stopPropagation();eliminate(x.dataset.bankEliminate);return}let a=e.target.closest('[data-bank-answer]');if(a&&!done)select(a.dataset.bankAnswer)});
}
function status(t,k='neutral'){let e=$('#bankStatus');if(e){e.textContent=t;e.dataset.kind=k}}
async function client(){if(window.mentorCloud?.client)return window.mentorCloud.client;if(!window.supabase?.createClient)throw Error('Supabase não carregou');return window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
async function load(){
if(!db)db=await client();let {data:{session}}=await db.auth.getSession();user=session?.user||null;
if(!user){bank=[];status('Entre na sua conta para acessar as questões privadas.','warn');if($('#bankHomeText'))$('#bankHomeText').textContent='Entre na conta para acessar as questões dos seus módulos.';counts();return}
status('Carregando inteligência de prova…','loading');
let {data,error}=await db.from('questions').select('id,exam_name,subject_label,topic_label,source_question_number,statement,alternatives,correct_answer,explanation,source_kind').not('explanation','is',null).order('created_at',{ascending:true}).limit(1000);if(error)throw error;bank=data||[];
states=new Map();let ids=bank.map(x=>x.id);if(ids.length){let r=await db.from('user_question_state').select('question_id,seen_count,correct_count,wrong_count,last_seen_at,next_review_at,status').in('question_id',ids);if(r.error)throw r.error;(r.data||[]).forEach(x=>states.set(x.question_id,x))}
subjects();topics();counts();status(bank.length?'Banco operacional. Escolha os filtros e inicie.':'Ainda não há questões liberadas no seu acervo.',bank.length?'ok':'warn');if($('#bankHomeText'))$('#bankHomeText').textContent=bank.length?`${bank.length} questões reais já estão disponíveis na central.`:'As questões estão sendo preparadas.'
}
function subjects(){let e=$('#bankSubject');if(!e)return;let old=e.value,v=[...new Set(bank.map(x=>x.subject_label).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));e.innerHTML='<option value="">Todas</option>'+v.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(v.includes(old))e.value=old}
function topics(){let s=$('#bankSubject')?.value||'',e=$('#bankTopic');if(!e)return;let old=e.value,v=[...new Set(bank.filter(x=>!s||x.subject_label===s).map(x=>x.topic_label).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));e.innerHTML='<option value="">Todos</option>'+v.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(v.includes(old))e.value=old}
function filtered(){let s=$('#bankSubject')?.value||'',t=$('#bankTopic')?.value||'';return bank.filter(x=>(!s||x.subject_label===s)&&(!t||x.topic_label===t))}
function counts(){let a=filtered(),n=a.filter(x=>!states.has(x.id)||!(states.get(x.id)?.seen_count)).length;if($('#bankTotal'))$('#bankTotal').textContent=a.length;if($('#bankNew'))$('#bankNew').textContent=n;if($('#bankSession'))$('#bankSession').textContent=`${ok}/${total}`}
function choose(){let a=filtered();if(!a.length)return null;let now=Date.now(),fresh=a.filter(x=>!states.has(x.id)||!states.get(x.id)?.seen_count),due=a.filter(x=>{let s=states.get(x.id);return s?.next_review_at&&new Date(s.next_review_at).getTime()<=now}),p=fresh.length?fresh:due.length?due:[...a].sort((x,y)=>(states.get(x.id)?.seen_count||0)-(states.get(y.id)?.seen_count||0)),m=Math.min(...p.map(x=>states.get(x.id)?.seen_count||0)),l=p.filter(x=>(states.get(x.id)?.seen_count||0)===m);return l[Math.floor(Math.random()*l.length)]||p[0]}
async function begin(){if(!db)db=await client();let {data:{session}}=await db.auth.getSession();if(!session?.user){window.mentorCloud?.openLogin?.();status('Entre na conta e toque novamente em iniciar.','warn');return}if(!bank.length)await load();q=choose();if(!q){status('Nenhuma questão encontrada nesse filtro.','warn');return}$('#bankOperational')?.classList.remove('hidden');show(q)}
function badge(x){let s=states.get(x.id);if(!s||!s.seen_count)return['NOVA','badge-novo'];if(s.status==='mastered')return['DOMINADA','badge-acerto'];if(s.status==='review'||s.wrong_count>0)return['REVISÃO','badge-erro'];return['APRENDENDO','badge-learning']}
function show(x){
q=x;done=false;choice=null;eliminated=new Set();start=Date.now();conf='medium';$$('[data-bank-confidence]').forEach(b=>{b.disabled=false;b.classList.toggle('active',b.dataset.bankConfidence==='medium')});$('#bankFeedback')?.classList.add('hidden');$('#bankConfirmBtn')?.classList.add('hidden');$('#bankNextBtn')?.classList.add('hidden');
let [t,c]=badge(x),b=$('#bankQuestionStatus');if(b){b.textContent=t;b.className=`qg-status-badge ${c}`}$('#bankQuestionSource').textContent=x.exam_name||'Seu módulo';$('#bankQuestionMeta').textContent=`QUESTÃO ${x.source_question_number||'—'}`;$('#bankQuestionSubject').textContent=x.subject_label||'Matéria';$('#bankQuestionTopic').textContent=x.topic_label||'Assunto';$('#bankStatement').textContent=x.statement;$('#bankProgress').textContent=`${total} respondida(s) nesta operação`;
let ent=Object.entries(x.alternatives||{}),elim=ent.length>2;$('#bankAnswers').innerHTML=ent.map(([l,text])=>`<div class="qg-option-wrapper" data-option-wrapper="${esc(l)}"><button class="qg-option-item" data-bank-answer="${esc(l)}"><span class="qg-option-letter">${esc(l)}</span><span>${esc(text)}</span></button>${elim?`<button class="qg-btn-eliminar" data-bank-eliminate="${esc(l)}" title="Eliminar alternativa">×</button>`:''}</div>`).join('');
tick();clearInterval(window.__mentorBankTimer);window.__mentorBankTimer=setInterval(tick,1000);$('#bankQuestionCard')?.scrollIntoView({behavior:'smooth',block:'start'})
}
function select(l){if(done||eliminated.has(l))return;choice=l;$$('[data-option-wrapper]').forEach(w=>w.classList.toggle('selected',w.dataset.optionWrapper===l));$('#bankConfirmBtn')?.classList.remove('hidden')}
function eliminate(l){if(done)return;let w=[...$$('[data-option-wrapper]')].find(x=>x.dataset.optionWrapper===l);if(!w)return;if(eliminated.has(l)){eliminated.delete(l);w.classList.remove('eliminated')}else{eliminated.add(l);w.classList.add('eliminated');if(choice===l){choice=null;w.classList.remove('selected');$('#bankConfirmBtn')?.classList.add('hidden')}}}
function tick(){let e=$('#bankTimer');if(!e||!start||done)return;let s=Math.floor((Date.now()-start)/1000);e.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
const confNum=()=>({low:2,medium:3,high:5}[conf]||3);
function mentor(correct,secs){if(correct&&conf==='high'&&secs<=45)return'Sinal forte de domínio. Se repetir esse padrão, posso aumentar a dificuldade ou avançar de assunto.';if(correct&&conf==='low')return'Acerto frágil: você acertou sem segurança. Vou testar esse conceito de novo antes de considerar domínio.';if(!correct&&conf==='high')return'Alerta de conceito: erro com confiança alta. Esta questão vira prioridade de revisão.';if(!correct&&conf==='low')return'Lacuna assumida: vou reforçar a base e trazer outra questão próxima.';return correct?'Bom sinal. Vou procurar consistência antes de liberar o tópico.':'Erro registrado. Vou usar essa evidência para decidir a revisão e a próxima questão.'}
async function confirm(){
if(!q||done||!choice)return;done=true;clearInterval(window.__mentorBankTimer);let secs=Math.max(1,Math.round((Date.now()-start)/1000)),right=String(q.correct_answer).toUpperCase(),sel=String(choice).toUpperCase(),correct=sel===right;total++;if(correct)ok++;
$$('[data-option-wrapper]').forEach(w=>{let l=w.dataset.optionWrapper;w.classList.remove('selected','eliminated');if(l===right)w.classList.add('correct');if(l===sel&&!correct)w.classList.add('wrong');w.querySelectorAll('button').forEach(b=>b.disabled=true)});$$('[data-bank-confidence]').forEach(b=>b.disabled=true);$('#bankConfirmBtn')?.classList.add('hidden');$('#bankNextBtn')?.classList.remove('hidden');
let f=$('#bankFeedback');f.className=`qg-comment-box ${correct?'good':'bad'}`;f.innerHTML=`<div class="qg-feedback-result">${correct?'✅ ALVO CONFIRMADO — ACERTO':`❌ RESPOSTA INCORRETA — GABARITO ${esc(right)}`}</div><div class="qg-analysis-title">💡 ANÁLISE DA MENTORA</div><p>${esc(q.explanation||'Explicação em preparação.')}</p><div class="qg-mentor-signal">${esc(mentor(correct,secs))}</div><small>Tempo: ${secs}s • Confiança: ${conf==='high'?'alta':conf==='low'?'baixa':'média'}${eliminated.size?` • ${eliminated.size} alternativa(s) eliminada(s)`:''}</small>`;$('#bankProgress').textContent=`${ok}/${total} acertos nesta operação`;counts();
try{await save(sel,correct,secs);mirror(correct,secs)}catch(e){console.error(e);f.insertAdjacentHTML('beforeend','<small class="qg-save-warning">⚠ Correção exibida, mas houve falha ao salvar na nuvem.</small>')}
}
function review(correct,n){let d=new Date();d.setDate(d.getDate()+(correct?(n>=2?14:7):1));return d.toISOString()}
async function save(letter,correct,secs){let {data:{session}}=await db.auth.getSession();user=session?.user;if(!user)throw Error('Sessão encerrada');let a=await db.from('question_attempts').insert({user_id:user.id,question_id:q.id,is_correct:correct,selected_answer:letter,correct_answer_snapshot:q.correct_answer,response_time_seconds:secs,confidence:confNum(),source_kind:q.source_kind||'personal_module'});if(a.error)throw a.error;let o=states.get(q.id)||{seen_count:0,correct_count:0,wrong_count:0},cc=(o.correct_count||0)+(correct?1:0),ww=(o.wrong_count||0)+(correct?0:1),row={user_id:user.id,question_id:q.id,seen_count:(o.seen_count||0)+1,correct_count:cc,wrong_count:ww,last_seen_at:new Date().toISOString(),next_review_at:review(correct,cc),status:correct?(cc>=2?'mastered':'learning'):'review',updated_at:new Date().toISOString()},r=await db.from('user_question_state').upsert(row,{onConflict:'user_id,question_id'});if(r.error)throw r.error;states.set(q.id,row);counts()}
function mirror(correct,secs){try{if(typeof state==='undefined'||typeof ensureTopic!=='function'||typeof scoreDelta!=='function')return;let name=ALIAS[q.subject_label]||q.subject_label,s=state.subjects?.[name];if(!s)return;let t=ensureTopic(s,q.topic_label||'Acervo'),delta=scoreDelta(correct,2,conf,secs),at=new Date().toISOString();[s,t].forEach(b=>{b.score=clamp(b.score+delta,15,95);b.evidence++;b.total++;b.correct+=correct?1:0;b.lastAttempt=at;if(!correct&&conf==='high')b.highConfidenceErrors=(b.highConfidenceErrors||0)+1});state.answered++;state.correct+=correct?1:0;state.attempts.push({id:`bank-${q.id}-${Date.now()}`,questionId:q.id,subject:name,topic:q.topic_label||'Acervo',difficulty:2,correct,selected:choice,confidence:conf,elapsed:secs,reasoning:'',delta,at,source:'Acervo PDF'});if(state.attempts.length>500)state.attempts=state.attempts.slice(-500);saveState();renderDashboard()}catch(e){console.warn(e)}}
function next(){let x=choose();if(!x){status('Você concluiu as questões disponíveis neste filtro por agora.','ok');return}show(x)}
async function boot(){theme();ui();version();try{db=await client();await load();db.auth.onAuthStateChange(e=>{if(e==='SIGNED_IN'||e==='SIGNED_OUT')setTimeout(()=>load().catch(console.error),50)})}catch(e){console.error(e);status('Não foi possível conectar ao banco agora.','error')}}
boot();
})();